/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_devproof.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_ledger_devproof.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */



MCPKG_API struct McPkgDevProof *mcpkg_mp_ledger_devproof_new(void)
{
	struct McPkgDevProof *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_ledger_devproof_free(struct McPkgDevProof *p)
{
	if (!p)
		return;

	/* free kind */
	/* free proof_data1 */
	free(p->proof_data1);
	p->proof_data1 = NULL;

	/* free proof_data2 */
	free(p->proof_data2);
	p->proof_data2 = NULL;

	/* free proof_sig */

	free(p);
}

MCPKG_API char *mcpkg_mp_ledger_devproof_debug_str(const struct McPkgDevProof
                *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgDevProof(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgDevProof{") < 0)
		goto oom;

	/* kind */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "kind=%u,",
	                             (unsigned int)p->kind) < 0)
		goto oom;

	/* proof_data1 */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             "proof_data1=%s,",
	                             p->proof_data1 ? p->proof_data1 : "NULL") < 0)
		goto oom;

	/* proof_data2 */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             "proof_data2=%s,",
	                             p->proof_data2 ? p->proof_data2 : "NULL") < 0)
		goto oom;

	/* proof_sig */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "proof_sig=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 64; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->proof_sig[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_ledger_devproof_pack(const struct McPkgDevProof *p,
                void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 6);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "ledger.devproof", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* kind */
	mpret = mcpkg_mp_kv_u32(&w, 2, p->kind);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* proof_data1 */
	if (p->proof_data1)
		mpret = mcpkg_mp_kv_str(&w, 3, p->proof_data1);
	else
		mpret = mcpkg_mp_kv_nil(&w, 3);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* proof_data2 */
	if (p->proof_data2)
		mpret = mcpkg_mp_kv_str(&w, 4, p->proof_data2);
	else
		mpret = mcpkg_mp_kv_nil(&w, 4);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* proof_sig */
	mpret = mcpkg_mp_kv_bin(&w, 5, p->proof_sig, 64);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_ledger_devproof_unpack(const void *buf, size_t len,
                struct McPkgDevProof **out_p)
{
	struct McPkgMpReader r;
	struct McPkgDevProof *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "ledger.devproof", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_ledger_devproof_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* kind */
	{
		uint32_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u32(&r, 2, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->kind = (int32_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* proof_data1 */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 3, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->proof_data1 = malloc(pl_ + 1);
			if (!p->proof_data1) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->proof_data1, ptr_, pl_);
			p->proof_data1[pl_] = '\0';
		}
	}

	/* proof_data2 */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 4, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->proof_data2 = malloc(pl_ + 1);
			if (!p->proof_data2) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->proof_data2, ptr_, pl_);
			p->proof_data2[pl_] = '\0';
		}
	}

	/* proof_sig */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 5, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_ && pl_ != 64) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 64)
			memcpy(p->proof_sig, ptr_, 64);
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_ledger_devproof_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
