/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/pkg/pkg_origin.yaml
 */

#ifndef MCPKG_MP_MP_PKG_ORIGIN_H
#define MCPKG_MP_MP_PKG_ORIGIN_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_PKG_ORIGIN_TAG "pkg.origin"
#define MCPKG_MP_MP_PKG_ORIGIN_VER 1


struct McPkgOrigin {
	char			*provider;
	char			*project_id;
	char			*version_id;
	char			*source_url;
};

MCPKG_API struct McPkgOrigin *mcpkg_mp_pkg_origin_new(void);
MCPKG_API void mcpkg_mp_pkg_origin_free(struct McPkgOrigin *p);

MCPKG_API int mcpkg_mp_pkg_origin_pack(const struct McPkgOrigin *p,
                                       void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_pkg_origin_unpack(const void *buf, size_t len,
                struct McPkgOrigin **out_p);

MCPKG_API char *mcpkg_mp_pkg_origin_debug_str(const struct McPkgOrigin *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_PKG_ORIGIN_H */
