/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/pkg/pkg_depends.yaml
 */

#ifndef MCPKG_MP_MP_PKG_DEPENDS_H
#define MCPKG_MP_MP_PKG_DEPENDS_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_PKG_DEPENDS_TAG "pkg.depends"
#define MCPKG_MP_MP_PKG_DEPENDS_VER 1


struct McPkgDepends {
	char			*id;
	char			*version_range;
	uint32_t		kind;
	int32_t			side;
};

MCPKG_API struct McPkgDepends *mcpkg_mp_pkg_depends_new(void);
MCPKG_API void mcpkg_mp_pkg_depends_free(struct McPkgDepends *p);

MCPKG_API int mcpkg_mp_pkg_depends_pack(const struct McPkgDepends *p,
                                        void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_pkg_depends_unpack(const void *buf, size_t len,
                struct McPkgDepends **out_p);

MCPKG_API char *mcpkg_mp_pkg_depends_debug_str(const struct McPkgDepends *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_PKG_DEPENDS_H */
