/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_tx.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_ledger_tx.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */



MCPKG_API struct McPkgTx *mcpkg_mp_ledger_tx_new(void)
{
	struct McPkgTx *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_ledger_tx_free(struct McPkgTx *p)
{
	if (!p)
		return;

	/* free from_pub */
	/* free to_pub */
	/* free amount */
	/* free nonce */
	/* free sig_from */

	free(p);
}

MCPKG_API char *mcpkg_mp_ledger_tx_debug_str(const struct McPkgTx *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgTx(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgTx{") < 0)
		goto oom;

	/* from_pub */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "from_pub=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 32; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->from_pub[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}

	/* to_pub */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "to_pub=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 32; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->to_pub[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}

	/* amount */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "amount=%llu,",
	                             (unsigned long long)p->amount) < 0)
		goto oom;

	/* nonce */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "nonce=%llu,",
	                             (unsigned long long)p->nonce) < 0)
		goto oom;

	/* sig_from */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "sig_from=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 64; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->sig_from[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_ledger_tx_pack(const struct McPkgTx *p,
                                      void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 7);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "ledger.tx", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* from_pub */
	mpret = mcpkg_mp_kv_bin(&w, 2, p->from_pub, 32);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* to_pub */
	mpret = mcpkg_mp_kv_bin(&w, 3, p->to_pub, 32);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* amount */
	/* encode u64 as i64 (non-negative) via util */
	mpret = mcpkg_mp_kv_i64(&w, 4, (int64_t)p->amount);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* nonce */
	/* encode u64 as i64 (non-negative) via util */
	mpret = mcpkg_mp_kv_i64(&w, 5, (int64_t)p->nonce);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* sig_from */
	mpret = mcpkg_mp_kv_bin(&w, 6, p->sig_from, 64);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_ledger_tx_unpack(const void *buf, size_t len,
                                        struct McPkgTx **out_p)
{
	struct McPkgMpReader r;
	struct McPkgTx *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "ledger.tx", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_ledger_tx_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* from_pub */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 2, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 32) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 32)
			memcpy(p->from_pub, ptr_, 32);
	}

	/* to_pub */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 3, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 32) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 32)
			memcpy(p->to_pub, ptr_, 32);
	}

	/* amount */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 4, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->amount = (int64_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* nonce */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 5, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->nonce = (int64_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* sig_from */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 6, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 64) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 64)
			memcpy(p->sig_from, ptr_, 64);
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_ledger_tx_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
