/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_audit_node.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_ledger_audit_node.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */



MCPKG_API struct McPkgAuditNode *mcpkg_mp_ledger_audit_node_new(void)
{
	struct McPkgAuditNode *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_ledger_audit_node_free(struct McPkgAuditNode *p)
{
	if (!p)
		return;

	/* free sibling */
	/* free is_right */

	free(p);
}

MCPKG_API char *mcpkg_mp_ledger_audit_node_debug_str(const struct McPkgAuditNode
                *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgAuditNode(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgAuditNode{") < 0)
		goto oom;

	/* sibling */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "sibling=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 32; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->sibling[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}

	/* is_right */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "is_right=%u,",
	                             (unsigned int)p->is_right) < 0)
		goto oom;


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_ledger_audit_node_pack(const struct McPkgAuditNode *p,
                void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 4);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "ledger.audit_node", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* sibling */
	mpret = mcpkg_mp_kv_bin(&w, 2, p->sibling, 32);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* is_right */
	mpret = mcpkg_mp_kv_u32(&w, 3, p->is_right);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_ledger_audit_node_unpack(const void *buf, size_t len,
                struct McPkgAuditNode **out_p)
{
	struct McPkgMpReader r;
	struct McPkgAuditNode *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "ledger.audit_node", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_ledger_audit_node_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* sibling */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 2, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 32) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 32)
			memcpy(p->sibling, ptr_, 32);
	}

	/* is_right */
	{
		uint32_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u32(&r, 3, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->is_right = (int32_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_ledger_audit_node_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
