/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_devlink.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_ledger_devlink.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */
#include "mp/mcpkg_mp_ledger_devproof.h"



MCPKG_API struct McPkgDevLink *mcpkg_mp_ledger_devlink_new(void)
{
	struct McPkgDevLink *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_ledger_devlink_free(struct McPkgDevLink *p)
{
	if (!p)
		return;

	/* free provider */
	free(p->provider);
	p->provider = NULL;

	/* free project_id */
	free(p->project_id);
	p->project_id = NULL;

	/* free dev_pub */
	/* free proof */
	if (p->proof) {
		mcpkg_mp_ledger_devproof_free(p->proof);
		p->proof = NULL;
	}

	/* free ts_ms */

	free(p);
}

MCPKG_API char *mcpkg_mp_ledger_devlink_debug_str(const struct McPkgDevLink *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgDevLink(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgDevLink{") < 0)
		goto oom;

	/* provider */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             " provider=%s,",
	                             p->provider ? p->provider : "NULL") < 0)
		goto oom;

	/* project_id */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             "project_id=%s,",
	                             p->project_id ? p->project_id : "NULL") < 0)
		goto oom;

	/* dev_pub */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "dev_pub=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 32; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->dev_pub[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}

	/* proof */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "proof=%s,",
	                             p->proof ? "set" : "NULL") < 0)
		goto oom;

	/* ts_ms */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "ts_ms=%lld,",
	                             (long long)p->ts_ms) < 0)
		goto oom;


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_ledger_devlink_pack(const struct McPkgDevLink *p,
                void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 7);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "ledger.devlink", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* provider */
	if (p->provider)
		mpret = mcpkg_mp_kv_str(&w, 2, p->provider);
	else
		mpret = mcpkg_mp_kv_nil(&w, 2);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* project_id */
	if (p->project_id)
		mpret = mcpkg_mp_kv_str(&w, 3, p->project_id);
	else
		mpret = mcpkg_mp_kv_nil(&w, 3);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* dev_pub */
	mpret = mcpkg_mp_kv_bin(&w, 4, p->dev_pub, 32);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* proof */
	if (p->proof) {
		void *b_ = NULL;
		size_t bl_ = 0;

		if (mcpkg_mp_ledger_devproof_pack(p->proof, &b_, &bl_) != MCPKG_MP_NO_ERROR) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_w;
		}
		mpret = mcpkg_mp_kv_bin(&w, 5, b_, (uint32_t)bl_);
		free(b_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_w;
	} else {
		mpret = mcpkg_mp_kv_nil(&w, 5);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_w;
	}

	/* ts_ms */
	mpret = mcpkg_mp_kv_i64(&w, 6, p->ts_ms);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_ledger_devlink_unpack(const void *buf, size_t len,
                struct McPkgDevLink **out_p)
{
	struct McPkgMpReader r;
	struct McPkgDevLink *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "ledger.devlink", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_ledger_devlink_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* provider */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 2, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->provider = malloc(pl_ + 1);
			if (!p->provider) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->provider, ptr_, pl_);
			p->provider[pl_] = '\0';
		}
		if (!found_ || !p->provider) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* project_id */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 3, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->project_id = malloc(pl_ + 1);
			if (!p->project_id) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->project_id, ptr_, pl_);
			p->project_id[pl_] = '\0';
		}
		if (!found_ || !p->project_id) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* dev_pub */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 4, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 32) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 32)
			memcpy(p->dev_pub, ptr_, 32);
	}

	/* proof */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 5, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;


		if (found_ && ptr_ && pl_ > 0) {
			if (mcpkg_mp_ledger_devproof_unpack(ptr_, pl_,
			                                    &p->proof) != MCPKG_MP_NO_ERROR) {
				mpret = MCPKG_MP_ERR_PARSE;
				goto out_err;
			}
		}
	}

	/* ts_ms */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 6, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->ts_ms = (int64_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_ledger_devlink_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
