/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_sth.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_ledger_sth.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */



MCPKG_API struct McPkgSTH *mcpkg_mp_ledger_sth_new(void)
{
	struct McPkgSTH *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_ledger_sth_free(struct McPkgSTH *p)
{
	if (!p)
		return;

	/* free size */
	/* free root */
	/* free ts_ms */
	/* free first */
	/* free last */

	free(p);
}

MCPKG_API char *mcpkg_mp_ledger_sth_debug_str(const struct McPkgSTH *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgSTH(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgSTH{") < 0)
		goto oom;

	/* size */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "size=%llu,",
	                             (unsigned long long)p->size) < 0)
		goto oom;

	/* root */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "root=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 32; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->root[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}

	/* ts_ms */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "ts_ms=%llu,",
	                             (unsigned long long)p->ts_ms) < 0)
		goto oom;

	/* first */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "first=%llu,",
	                             (unsigned long long)p->first) < 0)
		goto oom;

	/* last */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "last=%llu,",
	                             (unsigned long long)p->last) < 0)
		goto oom;


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_ledger_sth_pack(const struct McPkgSTH *p,
                                       void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 7);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "ledger.sth", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* size */
	/* encode u64 as i64 (non-negative) via util */
	mpret = mcpkg_mp_kv_i64(&w, 2, (int64_t)p->size);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* root */
	mpret = mcpkg_mp_kv_bin(&w, 3, p->root, 32);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* ts_ms */
	/* encode u64 as i64 (non-negative) via util */
	mpret = mcpkg_mp_kv_i64(&w, 4, (int64_t)p->ts_ms);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* first */
	/* encode u64 as i64 (non-negative) via util */
	mpret = mcpkg_mp_kv_i64(&w, 5, (int64_t)p->first);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* last */
	/* encode u64 as i64 (non-negative) via util */
	mpret = mcpkg_mp_kv_i64(&w, 6, (int64_t)p->last);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_ledger_sth_unpack(const void *buf, size_t len,
                struct McPkgSTH **out_p)
{
	struct McPkgMpReader r;
	struct McPkgSTH *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "ledger.sth", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_ledger_sth_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* size */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 2, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->size = (int64_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* root */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 3, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 32) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 32)
			memcpy(p->root, ptr_, 32);
	}

	/* ts_ms */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 4, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->ts_ms = (int64_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* first */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 5, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->first = (int64_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* last */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 6, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->last = (int64_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_ledger_sth_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
