/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_consistency.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_CONSISTENCY_H
#define MCPKG_MP_MP_LEDGER_CONSISTENCY_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"

#include "container/mcpkg_list.h"

MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_CONSISTENCY_TAG "ledger.consistency"
#define MCPKG_MP_MP_LEDGER_CONSISTENCY_VER 1


struct McPkgConsistencyProof {
	/* list of fixed-size byte arrays (32 bytes each) */
	struct McPkgList	*nodes;
};

MCPKG_API struct McPkgConsistencyProof *mcpkg_mp_ledger_consistency_new(void);
MCPKG_API void mcpkg_mp_ledger_consistency_free(struct McPkgConsistencyProof
                *p);

MCPKG_API int mcpkg_mp_ledger_consistency_pack(const struct
                McPkgConsistencyProof *p,
                void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_consistency_unpack(const void *buf, size_t len,
                struct McPkgConsistencyProof **out_p);

MCPKG_API char *mcpkg_mp_ledger_consistency_debug_str(const struct
                McPkgConsistencyProof *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_CONSISTENCY_H */
