/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_devsig.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_ledger_devsig.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */



MCPKG_API struct McPkgDevSig *mcpkg_mp_ledger_devsig_new(void)
{
	struct McPkgDevSig *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_ledger_devsig_free(struct McPkgDevSig *p)
{
	if (!p)
		return;

	/* free dev_pub */
	/* free manifest_sha256 */
	/* free sig_by_dev */

	free(p);
}

MCPKG_API char *mcpkg_mp_ledger_devsig_debug_str(const struct McPkgDevSig *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgDevSig(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgDevSig{") < 0)
		goto oom;

	/* dev_pub */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "dev_pub=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 32; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->dev_pub[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}

	/* manifest_sha256 */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "manifest_sha256=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 32; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->manifest_sha256[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}

	/* sig_by_dev */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "sig_by_dev=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 64; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->sig_by_dev[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_ledger_devsig_pack(const struct McPkgDevSig *p,
                void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 5);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "ledger.devsig", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* dev_pub */
	mpret = mcpkg_mp_kv_bin(&w, 2, p->dev_pub, 32);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* manifest_sha256 */
	mpret = mcpkg_mp_kv_bin(&w, 3, p->manifest_sha256, 32);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* sig_by_dev */
	mpret = mcpkg_mp_kv_bin(&w, 4, p->sig_by_dev, 64);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_ledger_devsig_unpack(const void *buf, size_t len,
                struct McPkgDevSig **out_p)
{
	struct McPkgMpReader r;
	struct McPkgDevSig *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "ledger.devsig", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_ledger_devsig_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* dev_pub */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 2, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 32) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 32)
			memcpy(p->dev_pub, ptr_, 32);
	}

	/* manifest_sha256 */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 3, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 32) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 32)
			memcpy(p->manifest_sha256, ptr_, 32);
	}

	/* sig_by_dev */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 4, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 64) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 64)
			memcpy(p->sig_by_dev, ptr_, 64);
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_ledger_devsig_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
