/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_attestation.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_ATTESTATION_H
#define MCPKG_MP_MP_LEDGER_ATTESTATION_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_ATTESTATION_TAG "ledger.attestation"
#define MCPKG_MP_MP_LEDGER_ATTESTATION_VER 1


struct McPkgAttestation {
	char			*pkg_id;
	char			*version;
	uint8_t			manifest_sha256[32];
	uint8_t			signer_pub[32];
	uint8_t			signature[64];
	int64_t			ts_ms;
};

MCPKG_API struct McPkgAttestation *mcpkg_mp_ledger_attestation_new(void);
MCPKG_API void mcpkg_mp_ledger_attestation_free(struct McPkgAttestation *p);

MCPKG_API int mcpkg_mp_ledger_attestation_pack(const struct McPkgAttestation *p,
                void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_attestation_unpack(const void *buf, size_t len,
                struct McPkgAttestation **out_p);

MCPKG_API char *mcpkg_mp_ledger_attestation_debug_str(const struct
                McPkgAttestation *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_ATTESTATION_H */
