/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_audit_node.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_AUDIT_NODE_H
#define MCPKG_MP_MP_LEDGER_AUDIT_NODE_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_AUDIT_NODE_TAG "ledger.audit_node"
#define MCPKG_MP_MP_LEDGER_AUDIT_NODE_VER 1


struct McPkgAuditNode {
	uint8_t			sibling[32];
	uint32_t		is_right;
};

MCPKG_API struct McPkgAuditNode *mcpkg_mp_ledger_audit_node_new(void);
MCPKG_API void mcpkg_mp_ledger_audit_node_free(struct McPkgAuditNode *p);

MCPKG_API int mcpkg_mp_ledger_audit_node_pack(const struct McPkgAuditNode *p,
                void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_audit_node_unpack(const void *buf, size_t len,
                struct McPkgAuditNode **out_p);

MCPKG_API char *mcpkg_mp_ledger_audit_node_debug_str(const struct McPkgAuditNode
                *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_AUDIT_NODE_H */
