/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_tx.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_TX_H
#define MCPKG_MP_MP_LEDGER_TX_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_TX_TAG "ledger.tx"
#define MCPKG_MP_MP_LEDGER_TX_VER 1


struct McPkgTx {
	uint8_t			from_pub[32];
	uint8_t			to_pub[32];
	uint64_t		amount;
	uint64_t		nonce;
	uint8_t			sig_from[64];
};

MCPKG_API struct McPkgTx *mcpkg_mp_ledger_tx_new(void);
MCPKG_API void mcpkg_mp_ledger_tx_free(struct McPkgTx *p);

MCPKG_API int mcpkg_mp_ledger_tx_pack(const struct McPkgTx *p,
                                      void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_tx_unpack(const void *buf, size_t len,
                                        struct McPkgTx **out_p);

MCPKG_API char *mcpkg_mp_ledger_tx_debug_str(const struct McPkgTx *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_TX_H */
