/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_devproof.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_DEVPROOF_H
#define MCPKG_MP_MP_LEDGER_DEVPROOF_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_DEVPROOF_TAG "ledger.devproof"
#define MCPKG_MP_MP_LEDGER_DEVPROOF_VER 1


struct McPkgDevProof {
	uint32_t		kind;
	char			*proof_data1;
	char			*proof_data2;
	uint8_t			proof_sig[64];
};

MCPKG_API struct McPkgDevProof *mcpkg_mp_ledger_devproof_new(void);
MCPKG_API void mcpkg_mp_ledger_devproof_free(struct McPkgDevProof *p);

MCPKG_API int mcpkg_mp_ledger_devproof_pack(const struct McPkgDevProof *p,
                void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_devproof_unpack(const void *buf, size_t len,
                struct McPkgDevProof **out_p);

MCPKG_API char *mcpkg_mp_ledger_devproof_debug_str(const struct McPkgDevProof
                *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_DEVPROOF_H */
