/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_block.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_ledger_block.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */
#include "mp/mcpkg_mp_ledger_sth.h"



MCPKG_API struct McPkgBlock *mcpkg_mp_ledger_block_new(void)
{
	struct McPkgBlock *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_ledger_block_free(struct McPkgBlock *p)
{
	if (!p)
		return;

	/* free height */
	/* free prev */
	/* free sth */
	if (p->sth) {
		mcpkg_mp_ledger_sth_free(p->sth);
		p->sth = NULL;
	}

	/* free mint_pub */
	/* free sig */

	free(p);
}

MCPKG_API char *mcpkg_mp_ledger_block_debug_str(const struct McPkgBlock *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgBlock(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgBlock{") < 0)
		goto oom;

	/* height */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "height=%llu,",
	                             (unsigned long long)p->height) < 0)
		goto oom;

	/* prev */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "prev=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 32; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->prev[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}

	/* sth */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "sth=%s,",
	                             p->sth ? "set" : "NULL") < 0)
		goto oom;

	/* mint_pub */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "mint_pub=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 32; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->mint_pub[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}

	/* sig */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "sig=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 64; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->sig[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_ledger_block_pack(const struct McPkgBlock *p,
                void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 7);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "ledger.block", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* height */
	/* encode u64 as i64 (non-negative) via util */
	mpret = mcpkg_mp_kv_i64(&w, 2, (int64_t)p->height);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* prev */
	mpret = mcpkg_mp_kv_bin(&w, 3, p->prev, 32);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* sth */
	if (p->sth) {
		void *b_ = NULL;
		size_t bl_ = 0;

		if (mcpkg_mp_ledger_sth_pack(p->sth, &b_, &bl_) != MCPKG_MP_NO_ERROR) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_w;
		}
		mpret = mcpkg_mp_kv_bin(&w, 4, b_, (uint32_t)bl_);
		free(b_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_w;
	} else {
		mpret = mcpkg_mp_kv_nil(&w, 4);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_w;
	}

	/* mint_pub */
	mpret = mcpkg_mp_kv_bin(&w, 5, p->mint_pub, 32);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* sig */
	mpret = mcpkg_mp_kv_bin(&w, 6, p->sig, 64);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_ledger_block_unpack(const void *buf, size_t len,
                struct McPkgBlock **out_p)
{
	struct McPkgMpReader r;
	struct McPkgBlock *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "ledger.block", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_ledger_block_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* height */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 2, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->height = (int64_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* prev */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 3, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 32) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 32)
			memcpy(p->prev, ptr_, 32);
	}

	/* sth */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 4, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || !ptr_ || pl_ == 0) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ > 0) {
			if (mcpkg_mp_ledger_sth_unpack(ptr_, pl_, &p->sth) != MCPKG_MP_NO_ERROR) {
				mpret = MCPKG_MP_ERR_PARSE;
				goto out_err;
			}
		}
	}

	/* mint_pub */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 5, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 32) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 32)
			memcpy(p->mint_pub, ptr_, 32);
	}

	/* sig */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 6, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 64) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 64)
			memcpy(p->sig, ptr_, 64);
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_ledger_block_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
