/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_hash32.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_HASH32_H
#define MCPKG_MP_MP_LEDGER_HASH32_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_HASH32_TAG "ledger.hash32"
#define MCPKG_MP_MP_LEDGER_HASH32_VER 1


struct McPkgHash32_MP {
	uint8_t			bytes[32];
};

MCPKG_API struct McPkgHash32_MP *mcpkg_mp_ledger_hash32_new(void);
MCPKG_API void mcpkg_mp_ledger_hash32_free(struct McPkgHash32_MP *p);

MCPKG_API int mcpkg_mp_ledger_hash32_pack(const struct McPkgHash32_MP *p,
                void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_hash32_unpack(const void *buf, size_t len,
                struct McPkgHash32_MP **out_p);

MCPKG_API char *mcpkg_mp_ledger_hash32_debug_str(const struct McPkgHash32_MP
                *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_HASH32_H */
