/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/pkg/pkg_file.yaml
 */

#ifndef MCPKG_MP_MP_PKG_FILE_H
#define MCPKG_MP_MP_PKG_FILE_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"

#include "container/mcpkg_list.h"

MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_PKG_FILE_TAG "pkg.file"
#define MCPKG_MP_MP_PKG_FILE_VER 1

struct McPkgDigest;

struct McPkgFile {
	char			*url;
	char			*file_name;
	uint64_t		size;
	/* list of struct McPkgDigest * */
	struct McPkgList	*digests;
};

MCPKG_API struct McPkgFile *mcpkg_mp_pkg_file_new(void);
MCPKG_API void mcpkg_mp_pkg_file_free(struct McPkgFile *p);

MCPKG_API int mcpkg_mp_pkg_file_pack(const struct McPkgFile *p,
                                     void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_pkg_file_unpack(const void *buf, size_t len,
                                       struct McPkgFile **out_p);

MCPKG_API char *mcpkg_mp_pkg_file_debug_str(const struct McPkgFile *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_PKG_FILE_H */
