/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_audit_path.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_AUDIT_PATH_H
#define MCPKG_MP_MP_LEDGER_AUDIT_PATH_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"

#include "container/mcpkg_list.h"

MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_AUDIT_PATH_TAG "ledger.audit_path"
#define MCPKG_MP_MP_LEDGER_AUDIT_PATH_VER 1

struct McPkgAuditNode;

struct McPkgAuditPath {
	/* list of struct McPkgAuditNode * */
	struct McPkgList	*nodes;
};

MCPKG_API struct McPkgAuditPath *mcpkg_mp_ledger_audit_path_new(void);
MCPKG_API void mcpkg_mp_ledger_audit_path_free(struct McPkgAuditPath *p);

MCPKG_API int mcpkg_mp_ledger_audit_path_pack(const struct McPkgAuditPath *p,
                void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_audit_path_unpack(const void *buf, size_t len,
                struct McPkgAuditPath **out_p);

MCPKG_API char *mcpkg_mp_ledger_audit_path_debug_str(const struct McPkgAuditPath
                *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_AUDIT_PATH_H */
