/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/pkg/pkg_digest.yaml
 */

#ifndef MCPKG_MP_MP_PKG_DIGEST_H
#define MCPKG_MP_MP_PKG_DIGEST_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_PKG_DIGEST_TAG "pkg.digest"
#define MCPKG_MP_MP_PKG_DIGEST_VER 1


struct McPkgDigest {
	uint32_t		algo;
	char			*hex;
};

MCPKG_API struct McPkgDigest *mcpkg_mp_pkg_digest_new(void);
MCPKG_API void mcpkg_mp_pkg_digest_free(struct McPkgDigest *p);

MCPKG_API int mcpkg_mp_pkg_digest_pack(const struct McPkgDigest *p,
                                       void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_pkg_digest_unpack(const void *buf, size_t len,
                struct McPkgDigest **out_p);

MCPKG_API char *mcpkg_mp_pkg_digest_debug_str(const struct McPkgDigest *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_PKG_DIGEST_H */
