/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/pkg/pkg_digest.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_pkg_digest.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */



MCPKG_API struct McPkgDigest *mcpkg_mp_pkg_digest_new(void)
{
	struct McPkgDigest *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_pkg_digest_free(struct McPkgDigest *p)
{
	if (!p)
		return;

	/* free algo */
	/* free hex */
	free(p->hex);
	p->hex = NULL;


	free(p);
}

MCPKG_API char *mcpkg_mp_pkg_digest_debug_str(const struct McPkgDigest *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgDigest(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgDigest{") < 0)
		goto oom;

	/* algo */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "algo=%u,",
	                             (unsigned int)p->algo) < 0)
		goto oom;

	/* hex */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             "hex=%s,",
	                             p->hex ? p->hex : "NULL") < 0)
		goto oom;


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_pkg_digest_pack(const struct McPkgDigest *p,
                                       void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 4);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "pkg.digest", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* algo */
	mpret = mcpkg_mp_kv_u32(&w, 2, p->algo);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* hex */
	if (p->hex)
		mpret = mcpkg_mp_kv_str(&w, 3, p->hex);
	else
		mpret = mcpkg_mp_kv_nil(&w, 3);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_pkg_digest_unpack(const void *buf, size_t len,
                struct McPkgDigest **out_p)
{
	struct McPkgMpReader r;
	struct McPkgDigest *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "pkg.digest", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_pkg_digest_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* algo */
	{
		uint32_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u32(&r, 2, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->algo = (int32_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* hex */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 3, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->hex = malloc(pl_ + 1);
			if (!p->hex) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->hex, ptr_, pl_);
			p->hex[pl_] = '\0';
		}
		if (!found_ || !p->hex) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_pkg_digest_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
