/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_consistency.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_ledger_consistency.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */



MCPKG_API struct McPkgConsistencyProof *mcpkg_mp_ledger_consistency_new(void)
{
	struct McPkgConsistencyProof *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_ledger_consistency_free(struct McPkgConsistencyProof *p)
{
	if (!p)
		return;

	/* free nodes */
	if (p->nodes) {
		mcpkg_list_free(p->nodes);
		p->nodes = NULL;
	}


	free(p);
}

MCPKG_API char *mcpkg_mp_ledger_consistency_debug_str(const struct
                McPkgConsistencyProof *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgConsistencyProof(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgConsistencyProof{") < 0)
		goto oom;

	/* nodes */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "nodes=[%zu],",
	                             p->nodes ? mcpkg_list_size(p->nodes) : 0ul) < 0)
		goto oom;


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_ledger_consistency_pack(const struct
                McPkgConsistencyProof *p,
                void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 3);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "ledger.consistency", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* nodes */
	{
		size_t i_, n_ = p->nodes ? mcpkg_list_size(p->nodes) : 0;

		mpret = mcpkg_mp_kv_array_begin(&w, 2, (uint32_t)n_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_w;

		for (i_ = 0; i_ < n_; i_++) {
			const void *elt_ = NULL;

			if (mcpkg_list_at(p->nodes, i_, &elt_) != MCPKG_CONTAINER_OK || !elt_) {
				mpret = MCPKG_MP_ERR_PARSE;
				goto out_w;
			}
			mpret = mcpkg_mp_write_bin(&w, elt_, 32);
			if (mpret != MCPKG_MP_NO_ERROR)
				goto out_w;
		}
	}


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_ledger_consistency_unpack(const void *buf, size_t len,
                struct McPkgConsistencyProof **out_p)
{
	struct McPkgMpReader r;
	struct McPkgConsistencyProof *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "ledger.consistency", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_ledger_consistency_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* nodes */
	{
		struct McPkgMpArrayCur *cur_ = NULL;
		size_t n_ = 0, i_;
		int found_ = 0;

		mpret = mcpkg_mp_get_array_cur(&r, 2, &cur_, &n_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;


		if (found_ && n_ > 0) {
			p->nodes = mcpkg_list_new(32, NULL, 0, 0);
			if (!p->nodes) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				mcpkg_mp_array_cur_destroy(cur_);
				goto out_err;
			}
			for (i_ = 0; i_ < n_; i_++) {
				const void *ptr_ = NULL;
				size_t pl_ = 0;

				if (mcpkg_mp_array_get_bin_borrow(cur_, i_, &ptr_, &pl_) != MCPKG_MP_NO_ERROR) {
					mcpkg_mp_array_cur_destroy(cur_);
					goto out_err;
				}
				if (pl_ != 32) {
					mcpkg_mp_array_cur_destroy(cur_);
					mpret = MCPKG_MP_ERR_PARSE;
					goto out_err;
				}
				if (mcpkg_list_push(p->nodes, ptr_) != MCPKG_CONTAINER_OK) {
					mcpkg_mp_array_cur_destroy(cur_);
					mpret = MCPKG_MP_ERR_NO_MEMORY;
					goto out_err;
				}
			}
		}

		if (cur_)
			mcpkg_mp_array_cur_destroy(cur_);
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_ledger_consistency_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
