/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_devsig.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_DEVSIG_H
#define MCPKG_MP_MP_LEDGER_DEVSIG_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_DEVSIG_TAG "ledger.devsig"
#define MCPKG_MP_MP_LEDGER_DEVSIG_VER 1


struct McPkgDevSig {
	uint8_t			dev_pub[32];
	uint8_t			manifest_sha256[32];
	uint8_t			sig_by_dev[64];
};

MCPKG_API struct McPkgDevSig *mcpkg_mp_ledger_devsig_new(void);
MCPKG_API void mcpkg_mp_ledger_devsig_free(struct McPkgDevSig *p);

MCPKG_API int mcpkg_mp_ledger_devsig_pack(const struct McPkgDevSig *p,
                void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_devsig_unpack(const void *buf, size_t len,
                struct McPkgDevSig **out_p);

MCPKG_API char *mcpkg_mp_ledger_devsig_debug_str(const struct McPkgDevSig *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_DEVSIG_H */
