/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_reward.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_REWARD_H
#define MCPKG_MP_MP_LEDGER_REWARD_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_REWARD_TAG "ledger.reward"
#define MCPKG_MP_MP_LEDGER_REWARD_VER 1


struct McPkgReward {
	uint8_t			to_pub[32];
	uint64_t		amount;
	char			*policy_id;
	uint64_t		att_ref;
	int64_t			ts_ms;
};

MCPKG_API struct McPkgReward *mcpkg_mp_ledger_reward_new(void);
MCPKG_API void mcpkg_mp_ledger_reward_free(struct McPkgReward *p);

MCPKG_API int mcpkg_mp_ledger_reward_pack(const struct McPkgReward *p,
                void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_reward_unpack(const void *buf, size_t len,
                struct McPkgReward **out_p);

MCPKG_API char *mcpkg_mp_ledger_reward_debug_str(const struct McPkgReward *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_REWARD_H */
