/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_devlink.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_DEVLINK_H
#define MCPKG_MP_MP_LEDGER_DEVLINK_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_DEVLINK_TAG "ledger.devlink"
#define MCPKG_MP_MP_LEDGER_DEVLINK_VER 1

struct McPkgDevProof;

struct McPkgDevLink {
	char			*provider;
	char			*project_id;
	uint8_t			dev_pub[32];
	struct McPkgDevProof	*proof;
	int64_t			ts_ms;
};

MCPKG_API struct McPkgDevLink *mcpkg_mp_ledger_devlink_new(void);
MCPKG_API void mcpkg_mp_ledger_devlink_free(struct McPkgDevLink *p);

MCPKG_API int mcpkg_mp_ledger_devlink_pack(const struct McPkgDevLink *p,
                void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_devlink_unpack(const void *buf, size_t len,
                struct McPkgDevLink **out_p);

MCPKG_API char *mcpkg_mp_ledger_devlink_debug_str(const struct McPkgDevLink *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_DEVLINK_H */
