/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/pkg/pkg_file.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_pkg_file.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */
#include "mp/mcpkg_mp_pkg_digest.h"



MCPKG_API struct McPkgFile *mcpkg_mp_pkg_file_new(void)
{
	struct McPkgFile *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_pkg_file_free(struct McPkgFile *p)
{
	if (!p)
		return;

	/* free url */
	free(p->url);
	p->url = NULL;

	/* free file_name */
	free(p->file_name);
	p->file_name = NULL;

	/* free size */
	/* free digests */
	if (p->digests) {
		size_t i_, n_ = mcpkg_list_size(p->digests);
		for (i_ = 0; i_ < n_; i_++) {
			struct McPkgDigest *elt_ = NULL;

			if (mcpkg_list_at(p->digests, i_, &elt_) == MCPKG_CONTAINER_OK && elt_)
				mcpkg_mp_pkg_digest_free(elt_);  // FIXME no header access
		}
		mcpkg_list_free(p->digests);
		p->digests = NULL;
	}


	free(p);
}

MCPKG_API char *mcpkg_mp_pkg_file_debug_str(const struct McPkgFile *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgFile(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgFile{") < 0)
		goto oom;

	/* url */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             " url=%s,",
	                             p->url ? p->url : "NULL") < 0)
		goto oom;

	/* file_name */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             "file_name=%s,",
	                             p->file_name ? p->file_name : "NULL") < 0)
		goto oom;

	/* size */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "size=%llu,",
	                             (unsigned long long)p->size) < 0)
		goto oom;

	/* digests */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "digests=[%zu],",
	                             p->digests ? mcpkg_list_size(p->digests) : 0ul) < 0)
		goto oom;


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_pkg_file_pack(const struct McPkgFile *p,
                                     void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 6);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "pkg.file", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* url */
	if (p->url)
		mpret = mcpkg_mp_kv_str(&w, 2, p->url);
	else
		mpret = mcpkg_mp_kv_nil(&w, 2);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* file_name */
	if (p->file_name)
		mpret = mcpkg_mp_kv_str(&w, 3, p->file_name);
	else
		mpret = mcpkg_mp_kv_nil(&w, 3);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* size */
	/* encode u64 as i64 (non-negative) via util */
	mpret = mcpkg_mp_kv_i64(&w, 4, (int64_t)p->size);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* digests */
	{
		size_t i_, n_ = p->digests ? mcpkg_list_size(p->digests) : 0;

		mpret = mcpkg_mp_kv_array_begin(&w, 5, (uint32_t)n_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_w;

		for (i_ = 0; i_ < n_; i_++) {
			struct McPkgDigest *elt_ = NULL;
			void *b_ = NULL;
			size_t bl_ = 0;

			if (mcpkg_list_at(p->digests, i_, &elt_) != MCPKG_CONTAINER_OK || !elt_) {
				mpret = MCPKG_MP_ERR_PARSE;
				goto out_w;
			}
			if (mcpkg_mp_pkg_digest_pack(elt_, &b_, &bl_) != MCPKG_MP_NO_ERROR) {
				mpret = MCPKG_MP_ERR_PARSE;
				goto out_w;
			}
			mpret = mcpkg_mp_write_bin(&w, b_, (uint32_t)bl_);
			free(b_);
			if (mpret != MCPKG_MP_NO_ERROR)
				goto out_w;
		}
	}


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_pkg_file_unpack(const void *buf, size_t len,
                                       struct McPkgFile **out_p)
{
	struct McPkgMpReader r;
	struct McPkgFile *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "pkg.file", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_pkg_file_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* url */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 2, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->url = malloc(pl_ + 1);
			if (!p->url) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->url, ptr_, pl_);
			p->url[pl_] = '\0';
		}
		if (!found_ || !p->url) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* file_name */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 3, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->file_name = malloc(pl_ + 1);
			if (!p->file_name) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->file_name, ptr_, pl_);
			p->file_name[pl_] = '\0';
		}
		if (!found_ || !p->file_name) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* size */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 4, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->size = (int64_t)val_;
	}

	/* digests */
	{
		struct McPkgMpArrayCur *cur_ = NULL;
		size_t n_ = 0;
		size_t i_;
		int found_ = 0;

		mpret = mcpkg_mp_get_array_cur(&r, 5, &cur_, &n_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			mcpkg_mp_array_cur_destroy(cur_);
			goto out_err;
		}

		if (found_ && n_ > 0) {
			/// yikes
			p->digests = mcpkg_list_new(sizeof(struct McPkgDigest *), NULL, 0, 0);
			if (!p->digests) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				mcpkg_mp_array_cur_destroy(cur_);
				goto out_err;
			}
			for (i_ = 0; i_ < n_; i_++) {
				const void *ptr_ = NULL;
				size_t pl_ = 0;
				struct McPkgDigest *elt_ = NULL;

				if (mcpkg_mp_array_get_bin_borrow(cur_, i_, &ptr_, &pl_) != MCPKG_MP_NO_ERROR) {
					mcpkg_mp_array_cur_destroy(cur_);
					goto out_err;
				}
				if (mcpkg_mp_pkg_digest_unpack(ptr_, pl_, &elt_) != MCPKG_MP_NO_ERROR) {
					mcpkg_mp_array_cur_destroy(cur_);
					mpret = MCPKG_MP_ERR_PARSE;
					goto out_err;
				}
				if (mcpkg_list_push(p->digests, &elt_) != MCPKG_CONTAINER_OK) {
					mcpkg_mp_pkg_digest_free(elt_);
					mcpkg_mp_array_cur_destroy(cur_);
					mpret = MCPKG_MP_ERR_NO_MEMORY;
					goto out_err;
				}
			}
		}

		if (cur_)
			mcpkg_mp_array_cur_destroy(cur_);
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_pkg_file_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
