/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/pkg/pkg_origin.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_pkg_origin.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */



MCPKG_API struct McPkgOrigin *mcpkg_mp_pkg_origin_new(void)
{
	struct McPkgOrigin *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_pkg_origin_free(struct McPkgOrigin *p)
{
	if (!p)
		return;

	/* free provider */
	free(p->provider);
	p->provider = NULL;

	/* free project_id */
	free(p->project_id);
	p->project_id = NULL;

	/* free version_id */
	free(p->version_id);
	p->version_id = NULL;

	/* free source_url */
	free(p->source_url);
	p->source_url = NULL;


	free(p);
}

MCPKG_API char *mcpkg_mp_pkg_origin_debug_str(const struct McPkgOrigin *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgOrigin(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgOrigin{") < 0)
		goto oom;

	/* provider */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             " provider=%s,",
	                             p->provider ? p->provider : "NULL") < 0)
		goto oom;

	/* project_id */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             "project_id=%s,",
	                             p->project_id ? p->project_id : "NULL") < 0)
		goto oom;

	/* version_id */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             "version_id=%s,",
	                             p->version_id ? p->version_id : "NULL") < 0)
		goto oom;

	/* source_url */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             "source_url=%s,",
	                             p->source_url ? p->source_url : "NULL") < 0)
		goto oom;


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_pkg_origin_pack(const struct McPkgOrigin *p,
                                       void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 6);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "pkg.origin", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* provider */
	if (p->provider)
		mpret = mcpkg_mp_kv_str(&w, 2, p->provider);
	else
		mpret = mcpkg_mp_kv_nil(&w, 2);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* project_id */
	if (p->project_id)
		mpret = mcpkg_mp_kv_str(&w, 3, p->project_id);
	else
		mpret = mcpkg_mp_kv_nil(&w, 3);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* version_id */
	if (p->version_id)
		mpret = mcpkg_mp_kv_str(&w, 4, p->version_id);
	else
		mpret = mcpkg_mp_kv_nil(&w, 4);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* source_url */
	if (p->source_url)
		mpret = mcpkg_mp_kv_str(&w, 5, p->source_url);
	else
		mpret = mcpkg_mp_kv_nil(&w, 5);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_pkg_origin_unpack(const void *buf, size_t len,
                struct McPkgOrigin **out_p)
{
	struct McPkgMpReader r;
	struct McPkgOrigin *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "pkg.origin", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_pkg_origin_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* provider */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 2, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->provider = malloc(pl_ + 1);
			if (!p->provider) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->provider, ptr_, pl_);
			p->provider[pl_] = '\0';
		}
		if (!found_ || !p->provider) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* project_id */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 3, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->project_id = malloc(pl_ + 1);
			if (!p->project_id) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->project_id, ptr_, pl_);
			p->project_id[pl_] = '\0';
		}
		if (!found_ || !p->project_id) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* version_id */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 4, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->version_id = malloc(pl_ + 1);
			if (!p->version_id) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->version_id, ptr_, pl_);
			p->version_id[pl_] = '\0';
		}
	}

	/* source_url */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 5, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->source_url = malloc(pl_ + 1);
			if (!p->source_url) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->source_url, ptr_, pl_);
			p->source_url[pl_] = '\0';
		}
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_pkg_origin_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
