/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/pkg/pkg_depends.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_pkg_depends.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */



MCPKG_API struct McPkgDepends *mcpkg_mp_pkg_depends_new(void)
{
	struct McPkgDepends *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_pkg_depends_free(struct McPkgDepends *p)
{
	if (!p)
		return;

	/* free id */
	free(p->id);
	p->id = NULL;

	/* free version_range */
	free(p->version_range);
	p->version_range = NULL;

	/* free kind */
	/* free side */

	free(p);
}

MCPKG_API char *mcpkg_mp_pkg_depends_debug_str(const struct McPkgDepends *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgDepends(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgDepends{") < 0)
		goto oom;

	/* id */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             " id=%s,",
	                             p->id ? p->id : "NULL") < 0)
		goto oom;

	/* version_range */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             "version_range=%s,",
	                             p->version_range ? p->version_range : "NULL") < 0)
		goto oom;

	/* kind */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "kind=%u,",
	                             (unsigned int)p->kind) < 0)
		goto oom;

	/* side */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "side=%d,",
	                             (int)p->side) < 0)
		goto oom;


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_pkg_depends_pack(const struct McPkgDepends *p,
                                        void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 6);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "pkg.depends", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* id */
	if (p->id)
		mpret = mcpkg_mp_kv_str(&w, 2, p->id);
	else
		mpret = mcpkg_mp_kv_nil(&w, 2);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* version_range */
	if (p->version_range)
		mpret = mcpkg_mp_kv_str(&w, 3, p->version_range);
	else
		mpret = mcpkg_mp_kv_nil(&w, 3);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* kind */
	mpret = mcpkg_mp_kv_u32(&w, 4, p->kind);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* side */
	mpret = mcpkg_mp_kv_i32(&w, 5, p->side);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_pkg_depends_unpack(const void *buf, size_t len,
                struct McPkgDepends **out_p)
{
	struct McPkgMpReader r;
	struct McPkgDepends *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "pkg.depends", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_pkg_depends_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* id */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 2, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->id = malloc(pl_ + 1);
			if (!p->id) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->id, ptr_, pl_);
			p->id[pl_] = '\0';
		}
		if (!found_ || !p->id) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* version_range */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 3, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->version_range = malloc(pl_ + 1);
			if (!p->version_range) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->version_range, ptr_, pl_);
			p->version_range[pl_] = '\0';
		}
		if (!found_ || !p->version_range) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* kind */
	{
		uint32_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u32(&r, 4, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->kind = (int32_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* side */
	{
		uint32_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u32(&r, 5, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->side = (int32_t)val_;
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_pkg_depends_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
