/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_delegate.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_ledger_delegate.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */



MCPKG_API struct McPkgDelegate *mcpkg_mp_ledger_delegate_new(void)
{
	struct McPkgDelegate *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_ledger_delegate_free(struct McPkgDelegate *p)
{
	if (!p)
		return;

	/* free dev_pub */
	/* free builder_pub */
	/* free project_id */
	free(p->project_id);
	p->project_id = NULL;

	/* free not_before_ms */
	/* free not_after_ms */
	/* free sig_by_dev */

	free(p);
}

MCPKG_API char *mcpkg_mp_ledger_delegate_debug_str(const struct McPkgDelegate
                *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgDelegate(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgDelegate{") < 0)
		goto oom;

	/* dev_pub */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "dev_pub=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 32; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->dev_pub[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}

	/* builder_pub */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "builder_pub=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 32; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->builder_pub[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}

	/* project_id */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             "project_id=%s,",
	                             p->project_id ? p->project_id : "NULL") < 0)
		goto oom;

	/* not_before_ms */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "not_before_ms=%lld,",
	                             (long long)p->not_before_ms) < 0)
		goto oom;

	/* not_after_ms */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "not_after_ms=%lld,",
	                             (long long)p->not_after_ms) < 0)
		goto oom;

	/* sig_by_dev */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "sig_by_dev=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 64; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->sig_by_dev[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_ledger_delegate_pack(const struct McPkgDelegate *p,
                void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 8);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "ledger.delegate", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* dev_pub */
	mpret = mcpkg_mp_kv_bin(&w, 2, p->dev_pub, 32);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* builder_pub */
	mpret = mcpkg_mp_kv_bin(&w, 3, p->builder_pub, 32);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* project_id */
	if (p->project_id)
		mpret = mcpkg_mp_kv_str(&w, 4, p->project_id);
	else
		mpret = mcpkg_mp_kv_nil(&w, 4);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* not_before_ms */
	mpret = mcpkg_mp_kv_i64(&w, 5, p->not_before_ms);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* not_after_ms */
	mpret = mcpkg_mp_kv_i64(&w, 6, p->not_after_ms);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* sig_by_dev */
	mpret = mcpkg_mp_kv_bin(&w, 7, p->sig_by_dev, 64);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_ledger_delegate_unpack(const void *buf, size_t len,
                struct McPkgDelegate **out_p)
{
	struct McPkgMpReader r;
	struct McPkgDelegate *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "ledger.delegate", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_ledger_delegate_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* dev_pub */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 2, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 32) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 32)
			memcpy(p->dev_pub, ptr_, 32);
	}

	/* builder_pub */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 3, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 32) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 32)
			memcpy(p->builder_pub, ptr_, 32);
	}

	/* project_id */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 4, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->project_id = malloc(pl_ + 1);
			if (!p->project_id) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->project_id, ptr_, pl_);
			p->project_id[pl_] = '\0';
		}
		if (!found_ || !p->project_id) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* not_before_ms */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 5, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->not_before_ms = (int64_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* not_after_ms */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 6, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->not_after_ms = (int64_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* sig_by_dev */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 7, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 64) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 64)
			memcpy(p->sig_by_dev, ptr_, 64);
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_ledger_delegate_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
