/* SPDX-License-Identifier: MIT */
/*
 * Auto-generated by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_reward.yaml
 */

#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>

#include "mp/mcpkg_mp_ledger_reward.h"

#include "mp/mcpkg_mp_util.h"
#include "container/mcpkg_list.h"
#include "container/mcpkg_str_list.h"

/* If we reference nested structs, pull in their generated headers. */



MCPKG_API struct McPkgReward *mcpkg_mp_ledger_reward_new(void)
{
	struct McPkgReward *p;

	p = calloc(1, sizeof(*p));
	return p;
}

MCPKG_API void mcpkg_mp_ledger_reward_free(struct McPkgReward *p)
{
	if (!p)
		return;

	/* free to_pub */
	/* free amount */
	/* free policy_id */
	free(p->policy_id);
	p->policy_id = NULL;

	/* free att_ref */
	/* free ts_ms */

	free(p);
}

MCPKG_API char *mcpkg_mp_ledger_reward_debug_str(const struct McPkgReward *p)
{
	char *s = NULL;
	size_t cap = 0, len = 0;

	if (!p)
		return mcpkg_mp_util_dup_str("McPkgReward(null)");

	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "McPkgReward{") < 0)
		goto oom;

	/* to_pub */
	{
		size_t i_;

		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "to_pub=0x") < 0)
			goto oom;
		for (i_ = 0; i_ < 32; i_++) {
			if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "%02x",
			                             (unsigned int)p->to_pub[i_]) < 0)
				goto oom;
		}
		if (mcpkg_mp_util_dbg_append(&s, &cap, &len, ",") < 0)
			goto oom;
	}

	/* amount */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "amount=%llu,",
	                             (unsigned long long)p->amount) < 0)
		goto oom;

	/* policy_id */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len,
	                             "policy_id=%s,",
	                             p->policy_id ? p->policy_id : "NULL") < 0)
		goto oom;

	/* att_ref */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "att_ref=%llu,",
	                             (unsigned long long)p->att_ref) < 0)
		goto oom;

	/* ts_ms */
	if (mcpkg_mp_util_dbg_append(&s, &cap, &len, "ts_ms=%lld,",
	                             (long long)p->ts_ms) < 0)
		goto oom;


	if (len > 0 && s[len - 1] == ',')
		s[len - 1] = '}';
	else
		(void)mcpkg_mp_util_dbg_append(&s, &cap, &len, "}");

	return s;
oom:
	free(s);
	return NULL;
}



MCPKG_API int mcpkg_mp_ledger_reward_pack(const struct McPkgReward *p,
                void **out_buf, size_t *out_len)
{
	struct McPkgMpWriter w;
	int mpret;

	if (!p || !out_buf || !out_len)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_writer_init(&w);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	/* header(2) + all fields (pack nil for missing optionals) */
	mpret = mcpkg_mp_map_begin(&w, 7);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	mpret = mcpkg_mp_write_header(&w, "ledger.reward", 1);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* to_pub */
	mpret = mcpkg_mp_kv_bin(&w, 2, p->to_pub, 32);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* amount */
	/* encode u64 as i64 (non-negative) via util */
	mpret = mcpkg_mp_kv_i64(&w, 3, (int64_t)p->amount);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* policy_id */
	if (p->policy_id)
		mpret = mcpkg_mp_kv_str(&w, 4, p->policy_id);
	else
		mpret = mcpkg_mp_kv_nil(&w, 4);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* att_ref */
	/* encode u64 as i64 (non-negative) via util */
	mpret = mcpkg_mp_kv_i64(&w, 5, (int64_t)p->att_ref);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;

	/* ts_ms */
	mpret = mcpkg_mp_kv_i64(&w, 6, p->ts_ms);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_w;


	mpret = mcpkg_mp_writer_finish(&w, out_buf, out_len);
out_w:
	mcpkg_mp_writer_destroy(&w);
	return mpret;
}


MCPKG_API int mcpkg_mp_ledger_reward_unpack(const void *buf, size_t len,
                struct McPkgReward **out_p)
{
	struct McPkgMpReader r;
	struct McPkgReward *p = NULL;
	int mpret, ver = 0;

	if (!buf || !len || !out_p)
		return MCPKG_MP_ERR_INVALID_ARG;

	mpret = mcpkg_mp_reader_init(&r, buf, len);
	if (mpret != MCPKG_MP_NO_ERROR)
		return mpret;

	mpret = mcpkg_mp_expect_tag(&r, "ledger.reward", &ver);
	if (mpret != MCPKG_MP_NO_ERROR)
		goto out_r;

	p = mcpkg_mp_ledger_reward_new();
	if (!p) {
		mpret = MCPKG_MP_ERR_NO_MEMORY;
		goto out_r;
	}

	/* to_pub */
	{
		const void *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_bin_borrow(&r, 2, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (!found_ || pl_ != 32) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}

		if (found_ && ptr_ && pl_ == 32)
			memcpy(p->to_pub, ptr_, 32);
	}

	/* amount */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 3, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->amount = (int64_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* policy_id */
	{
		const char *ptr_ = NULL;
		size_t pl_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_str_borrow(&r, 4, &ptr_, &pl_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_ && ptr_) {
			p->policy_id = malloc(pl_ + 1);
			if (!p->policy_id) {
				mpret = MCPKG_MP_ERR_NO_MEMORY;
				goto out_err;
			}
			memcpy(p->policy_id, ptr_, pl_);
			p->policy_id[pl_] = '\0';
		}
		if (!found_ || !p->policy_id) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* att_ref */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 5, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->att_ref = (int64_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}

	/* ts_ms */
	{
		uint64_t val_ = 0;
		int found_ = 0;

		mpret = mcpkg_mp_get_u64(&r, 6, &val_, &found_);
		if (mpret != MCPKG_MP_NO_ERROR)
			goto out_err;

		if (found_)
			p->ts_ms = (int64_t)val_;
		if (!found_) {
			mpret = MCPKG_MP_ERR_PARSE;
			goto out_err;
		}
	}


	*out_p = p;
	mcpkg_mp_reader_destroy(&r);
	return MCPKG_MP_NO_ERROR;

out_err:
	mcpkg_mp_ledger_reward_free(p);
out_r:
	mcpkg_mp_reader_destroy(&r);
	return mpret;
}
