/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_block.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_BLOCK_H
#define MCPKG_MP_MP_LEDGER_BLOCK_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_BLOCK_TAG "ledger.block"
#define MCPKG_MP_MP_LEDGER_BLOCK_VER 1

struct McPkgSTH;

struct McPkgBlock {
	uint64_t		height;
	uint8_t			prev[32];
	struct McPkgSTH	*sth;
	uint8_t			mint_pub[32];
	uint8_t			sig[64];
};

MCPKG_API struct McPkgBlock *mcpkg_mp_ledger_block_new(void);
MCPKG_API void mcpkg_mp_ledger_block_free(struct McPkgBlock *p);

MCPKG_API int mcpkg_mp_ledger_block_pack(const struct McPkgBlock *p,
                void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_block_unpack(const void *buf, size_t len,
                struct McPkgBlock **out_p);

MCPKG_API char *mcpkg_mp_ledger_block_debug_str(const struct McPkgBlock *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_BLOCK_H */
