/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_delegate.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_DELEGATE_H
#define MCPKG_MP_MP_LEDGER_DELEGATE_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_DELEGATE_TAG "ledger.delegate"
#define MCPKG_MP_MP_LEDGER_DELEGATE_VER 1


struct McPkgDelegate {
	uint8_t			dev_pub[32];
	uint8_t			builder_pub[32];
	char			*project_id;
	int64_t			not_before_ms;
	int64_t			not_after_ms;
	uint8_t			sig_by_dev[64];
};

MCPKG_API struct McPkgDelegate *mcpkg_mp_ledger_delegate_new(void);
MCPKG_API void mcpkg_mp_ledger_delegate_free(struct McPkgDelegate *p);

MCPKG_API int mcpkg_mp_ledger_delegate_pack(const struct McPkgDelegate *p,
                void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_delegate_unpack(const void *buf, size_t len,
                struct McPkgDelegate **out_p);

MCPKG_API char *mcpkg_mp_ledger_delegate_debug_str(const struct McPkgDelegate
                *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_DELEGATE_H */
