/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_revoke.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_REVOKE_H
#define MCPKG_MP_MP_LEDGER_REVOKE_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_REVOKE_TAG "ledger.revoke"
#define MCPKG_MP_MP_LEDGER_REVOKE_VER 1


struct McPkgRevoke {
	uint32_t		kind;
	uint8_t			target_hash[32];
	char			*pkg_id;
	char			*version;
	uint32_t		reason;
	int64_t			ts_ms;
};

MCPKG_API struct McPkgRevoke *mcpkg_mp_ledger_revoke_new(void);
MCPKG_API void mcpkg_mp_ledger_revoke_free(struct McPkgRevoke *p);

MCPKG_API int mcpkg_mp_ledger_revoke_pack(const struct McPkgRevoke *p,
                void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_revoke_unpack(const void *buf, size_t len,
                struct McPkgRevoke **out_p);

MCPKG_API char *mcpkg_mp_ledger_revoke_debug_str(const struct McPkgRevoke *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_REVOKE_H */
