/* SPDX-License-Identifier: MIT */
/*
 * AUTOGENERATED by mpgen — DO NOT EDIT BY HAND.
 * Source schema: /home/jmills/git/opensource/mcpkg/mpgen/schemas/ledger/ledger_sth.yaml
 */

#ifndef MCPKG_MP_MP_LEDGER_STH_H
#define MCPKG_MP_MP_LEDGER_STH_H

#include <stddef.h>
#include <stdint.h>

#include "mcpkg_export.h"


MCPKG_BEGIN_DECLS

#define MCPKG_MP_MP_LEDGER_STH_TAG "ledger.sth"
#define MCPKG_MP_MP_LEDGER_STH_VER 1


struct McPkgSTH {
	uint64_t		size;
	uint8_t			root[32];
	uint64_t		ts_ms;
	uint64_t		first;
	uint64_t		last;
};

MCPKG_API struct McPkgSTH *mcpkg_mp_ledger_sth_new(void);
MCPKG_API void mcpkg_mp_ledger_sth_free(struct McPkgSTH *p);

MCPKG_API int mcpkg_mp_ledger_sth_pack(const struct McPkgSTH *p,
                                       void **out_buf, size_t *out_len);

MCPKG_API int mcpkg_mp_ledger_sth_unpack(const void *buf, size_t len,
                struct McPkgSTH **out_p);

MCPKG_API char *mcpkg_mp_ledger_sth_debug_str(const struct McPkgSTH *p);

MCPKG_END_DECLS

#endif	/* MCPKG_MP_MP_LEDGER_STH_H */
